### ISSUE TITLE
The units for QSUB_LIQ and QSUR_LIQ appear incorrect.

### ISSUE THREAD

**Issue by angjuny** [IMMM-SFA/mosartwmpy#106]
The QSUR_LIQ and QSUB_LIQ variables show a unit of m/s although they are calculated from input runoff (mm/s) x land_frac (-) x area (m^2) x unit_conversion (mm to m). It can be confusing as the input runoff variables (QOVER and QDRAI) also have a similar unit of mm/s with the identical standard names (surface runoff and subsurface runoff).

**Comment by thurber** [comment]
thanks @angjuny, good catch! so should be labeled as m3/s correct?

**Comment by angjuny** [comment]
> thanks @angjuny, good catch! so should be labeled as m3/s correct?

Yes!
