### ISSUE TITLE
JOSS-REVIEW: tests

### ISSUE THREAD

**Issue by JannisHoch** [IMMM-SFA/mosartwmpy#37]
Dear @thurber,

great that you included tests in your package.
I think they are covering the main functions of the BMI model, but I still think one addition would be good: check whether the set_value(), get_value() functions yield the correct results. In my opinion, these functions are the main BMI functions in addition to initialize() and update(). While the latter two are covered, testing the first two should be included!

Thanks!

**Comment by thurber** [comment]
This is a good point, I will work on it next week

**Comment by thurber** [comment]
@JannisHoch, we've added some unit tests for testing the input/output BMI methods in PR #38. I'll merge it into `main` shortly which will close this issue, but feel free too reopen if not sufficiently addressed!

Linking to openjournals/joss-reviews#3221 for posterity.
