### ISSUE TITLE
JOSS-REVIEW: paper

### ISSUE THREAD

**Issue by JannisHoch** [IMMM-SFA/mosartwmpy#39]
Dear @thurber,

I have started reviewing the JOSS paper.

Here a few comments that should be included in a revised version:
- In the first paragraph of the 'Statement of Need' replace 'tightly-coupled codebase' with 'code' or something that is easier to understand for a less expert audience.
- While it's in there, I recommend to more clearly specify in 'Statement of Need' what the problem is your software aims to solve and what the intended audience is.
- It is not clear why you include BMI functionality. Any particular use case for it?
- Talking about BMI, I feel that you work is very close to some work of mine in which I added a BMI to various hydrological models and put them into a modelling framework (https://doi.org/10.5194/nhess-19-1723-2019). This would be a good addition to the BMI section of the paper and would fill in some content for the section 'State of the field' which is not yet really apparent in the paper.
- As such, please add a 'State of the field' section or at least a section that covers the relevant content.
- It is not clear whether the 'old' FORTRAN version is now replaced with the Python version or, if not, they are updated when model code changes in one of the versions. Please explain (briefly) how this refactoring of the model affects long-term model development. 
- The section 'Functionalities and limitations' is sligthly too technical for a JOSS paper (in my opinion). Please remove or rewrite it such that it appeals to a non-expert audience.

Besides these points, well-written paper and also references are fine.

Thanks for addressing these points.

**Comment by thurber** [comment]
Thanks for this feedback @JannisHoch! I'm going to think through how to address these points and will have a Pull Request ready in a couple days.

tagging https://github.com/openjournals/joss-reviews/issues/3221 for posterity

**Comment by JannisHoch** [comment]
@thurber happy with the modifications!
