### ISSUE TITLE
[JOSS review] Logging and verbosity

### ISSUE THREAD

**Issue by cheginit** [IMMM-SFA/mosartwmpy#41]
Since many Python users use Jupyter as their IDE, the logging info should be redirected to `stdout` so the logs don't show up with red background. You can do so by configuring the logger, for example, as follows:

```python
import logging
import sys

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(logging.Formatter(""))
logger.handlers = [handler]
logger.propagate = False
```

Also, the model is unnecessarily verbose by default. It might not matter much when you run the code via command-line but when you run it via Jupyter it causes issues. A much better approach is to use `tqdm`. I think a quick fix can be reducing the verbosity by default.

EDIT: Reference to openjournals/joss-reviews#3221

**Comment by cheginit** [comment]
Here's an example screenshot from Jupyter:
![image](https://user-images.githubusercontent.com/13016644/120224913-f07ab580-c209-11eb-9150-9f3c95c71da8.png)

**Comment by thurber** [comment]
This is a good point, I can adjust the majority of the logging to be debug level, and only echo the configuration into the file logger.

Curious, from your perspective, is logging the current timestep useful? Perhaps just at daily or monthly or yearly intervals?

**Comment by cheginit** [comment]
I think if you go with `tqdm` daily is fine. Otherwise, I think monthly or yearly works better as you said. I wonder if you tested the impact of logging on the performance? Since IO can sometimes affect the performance significantly, depending on the time each time-step takes.
