### ISSUE TITLE
submit `mosartwmpy` to conda-forge

### ISSUE THREAD

**Issue by thurber** [IMMM-SFA/mosartwmpy#47]

**Comment by cheginit** [comment]
It's pretty straightforward. You should start from [staged-recipes](https://github.com/conda-forge/staged-recipes). Using [`grayskull`](https://github.com/conda-incubator/grayskull) makes things very easy. It usually takes a couple of days to be approved.

**Comment by JannisHoch** [comment]
i am very much in favour of this. from my experience, working with `conda` is more widespread than using `pyenv`. as i have troubles myself to understand how `pyenv` works and to test `mosartwmpy`, having a (additional) conda-forge version would be great.

**Comment by thurber** [comment]
I've got `mosartwmpy` staged to be deployed on conda-forge at https://github.com/conda-forge/staged-recipes/pull/15186

**Comment by thurber** [comment]
addressed by #50

**Comment by JannisHoch** [comment]
great this works.
not obligatory, but maybe add the conda channel in the installation instructions, i.e.

`conda install -c conda-forge mosartwmpy`
