### ISSUE TITLE
remove `h5netcdf` dependency

### ISSUE THREAD

**Issue by thurber** [IMMM-SFA/mosartwmpy#48]

**Comment by thurber** [comment]
@cheginit, upon looking into this some more, the reason `h5netcdf` is used is because the `engine=netcdf4` doesn't allow reading from bit streams or file-like objects, such as directly out of a zipped file. I think the strategy for saving a grid state needs a little work anyway, so i'll save this ticket for a refactor in the future.

**Comment by cheginit** [comment]
In my experience, `scipy` handles bytes better. Here's how I use it for converting a list of byte responses (for example, from `r.content()`) to `xarray`:
```python
import io

ds = xr.open_mfdataset((io.BytesIO(r) for r in resp), engine="scipy", coords="minimal")
```

**Comment by thurber** [comment]
i see, that does limit one to NETCDF3, but it doesn't change the file size in this case, so i will implement. thanks!

**Comment by cheginit** [comment]
That's right. It converts it to NETCDF3_64BIT that fortunately can handle large netcdf files.
