### ISSUE TITLE
JOSS-REVIEW: documentation

### ISSUE THREAD

**Issue by JannisHoch** [IMMM-SFA/mosartwmpy#49]
hi @thurber,

i find the documentation overall good, but also pretty concise.
it would be great to include a jupyter notebook with an example application of your model.
this would not only give users an idea how a typical model workflow would look like, but also provide you with an opportunity to explain the model's functionality and set-up step-by-step and in greater detail.

i furthermore would like to see a 'statement of need' (similar as in the paper) in the documentation. not everyone is going to read the paper, but many will just go through the readme or rtd.

reference to: https://github.com/openjournals/joss-reviews/issues/3221.

**Comment by JannisHoch** [comment]
in addition to this:
the example application could be based on example data (if their size allows), which in turn could be used to provide a simple model which users can use to discover and play around with model functionalities.

**Comment by thurber** [comment]
good idea, i'll add a jupyter notebook with the tutorial inside it

**Comment by cheginit** [comment]
@thurber Since you're working on the documentation, just wanted to remind you to update the installation instructions (using Python 3.7+)

**Comment by thurber** [comment]
I added a Jupyter notebook tutorial in pull request #50!

**Comment by thurber** [comment]
addressed by #50

**Comment by JannisHoch** [comment]
@thurber,

documentation in general is improved.
last thing i'd  recommend is to link the notebook you have under `notebooks` to the readthedocs-documentation via the nblink extension. the package to install is nbconvert (https://nbconvert.readthedocs.io/en/latest/) and then link a `ipynb.nblink` file in index.rst file.
the nblink-file should include a relative path to the ipynb-file, looking like that:

```
{
    "path": "../../filename.ipynb"
}
```
