### ISSUE TITLE
JOSS-REVIEW: last minor issues

### ISSUE THREAD

**Issue by JannisHoch** [IMMM-SFA/mosartwmpy#52]
dear @thurber,

i have managed to install the package with conda now, and it works. great!

a few minor issues should be solved before i will give my green light for publication:

- [x] see my comment in the solved issue #49;
- [x] another one I have placed in #47;
- [x] please include `ipython` to the dependency list. this way, users can explore the model's functions more interactively;

not required for JOSS, but always great if available:

- [ ] make the notebook interactive with binder (https://mybinder.org/)

let me know if at least the top three are implemented.
looking forward to it!

**Comment by thurber** [comment]
thanks @JannisHoch, I've addressed your first three points in PR #53 if you want to check out the changes -- conda-forge is currently rebuilding and should be ready soonish~

**Comment by JannisHoch** [comment]
Great, looks good to me. Thanks for addressing all comments!

**Comment by thurber** [comment]
closed by #53
