### ISSUE TITLE
Implement farmer crop ABM into mosartwmpy

### ISSUE THREAD

**Issue by thurber** [IMMM-SFA/mosartwmpy#66]
Transfer Jim's Agent Based Model of farmer crop rotation into `mosartwmpy` (it is currently only implemented in `iwmm`)

**Comment by thurber** [comment]
notes from 1/12

Farmer ABM

files
* nldas_ids.p - not scenario specific
* nldas.txt - not scenario specific
* water_constraints_by_farm_pyt278.p - not used
* hist_avail_bias_correction_20201102.csv - based on ABM calibration
* hist_avail_bias_correction_live.csv - written each time
* hist_dependent_storage.csv - based on ABM calibration (historic run -> average historic storage levels)
* MOSART_WM_PMP_inputs_20201028.xlsx - ABM calibration / scenario conditions (could change based on scenario)
  * has some duplicated data with the below
* crop_ids_by_farm.p - join of farms to crops (probably can be done all in code)
* max_land_constr_20201102_protocol2.p - scenario specific
* gammas_new_20201102_protocol2.p - calibration
* net_prices_new_20201102_protocol2.p - calibration
* 25583.64 - sqft to acre - 
* abm_results_ - these outputs have individual agent crop land allocations for each year -> ultimately converted to demand
* lines 274 - 277 - alignment of grid cell with nldas id



demand flags / returnflow /groundwater
* needs to be ready in tandem with ABM


near term experiments:
* groundwater capability: mid-2022
  * cover historical period

wishlist:
* class instance for each agent (i.e. grid cell)
* currently, all agent decisions are solved in single optimization problem,
  but pyomo may not be optimal for solving single problems (but may be efficient at
  batches of ~1000 agents)

**Comment by thurber** [comment]
notes from DSC meeting:

- ask Jim if any of the input data is at all proprietary
- consider partitioning the mosartwmpy installation based on whether or not ABM is needed (i.e. `pip install mosartwmpy[abm]`
- consider the implications of the solver -- could we write our own (community may discredit it)? could we better optimize the way pyomo is called?

**Comment by erexer** [comment]
DSC meeting notes cont:
* check that Pyomo solvers aren't proprietary

**Comment by erexer** [comment]
closed by https://github.com/IMMM-SFA/mosartwmpy/pull/74
