### ISSUE TITLE
better error messages for missing data

### ISSUE THREAD

**Issue by thurber** [IMMM-SFA/mosartwmpy#76]
currently if you try running a simulation for a time period in which you are missing input data, wmpy will spit out a huge illegible stack trace that just means it can't find the data... need to catch these errors and give friendly messages

**Comment by DipayanP007** [comment]
Hey @thurber can I work on this?

**Comment by thurber** [comment]
@DipayanP007, sure thing! These two files are the main offenders:
* `mosartwmpy/input/demand.py`
* `mosartwmpy/input/runoff.py`

There are two failure modes -- either the file specified in the configuration doesn't exist, or it exists and has a time dimension but does not have any data close to the current timestep
